[tool.ruff]
target-version = "py310"
line-length = 100
src = ["app"]
exclude = [
  ".git",
  ".ruff_cache",
  "__pycache__",
  "build",
  "dist",
  "venv",
  ".venv",
  ".vscode"
]

[tool.ruff.lint]
select = [
  "E",   # pycodestyle errors
  "F",   # pyflakes
  "I",   # isort (import sorting)
  "UP"   # pyupgrade
]
ignore = []

[tool.ruff.lint.isort]
known-first-party = ["app"]
combine-as-imports = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"


